services:
  logtrack:
    build: .
    container_name: logtrack
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - instance_data:/app/instance
      - uploads_data:/app/uploads

volumes:
  instance_data:
  uploads_data:
