services:
  logtrack:
    build: .
    container_name: logtrack
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - instance_data:/app/instance
      - uploads_data:/app/uploads
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logtrack.rule=Host(`logtrack.renatomota.online`)"
      - "traefik.http.routers.logtrack.entrypoints=websecure"
      - "traefik.http.routers.logtrack.tls.certresolver=mytlschallenge"
      - "traefik.http.services.logtrack.loadbalancer.server.port=3000"

networks:
  n8n_default:
    external: true

volumes:
  instance_data:
  uploads_data:
